version: "3.7"

services:
  database:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    restart: always
    env_file: .env
    command: 
      - ./scripts/wait-for-it.sh database:${POSTGRES_PORT} --strict --timeout=300 -- /usr/bin/secret
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: